### ISSUE TITLE
unhandled promise rejection

### ISSUE THREAD

**Issue by Ilovegym66** [instalator/ioBroker.synology#41]
Hi,
with actual version 0.1.9 from github are these errors:
`

synology.0 | 2020-05-10 17:29:55.674 | info | (18900) terminating
-- | -- | -- | --
synology.0 | 2020-05-10 17:29:55.661 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
synology.0 | 2020-05-10 17:29:55.661 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8147:76
synology.0 | 2020-05-10 17:29:55.661 | error | at Object.main [as ready] (/opt/iobroker/node_modules/iobroker.synology/main.js:863:8)
synology.0 | 2020-05-10 17:29:55.661 | error | at Object.copyFileSync (fs.js:1800:3)
synology.0 | 2020-05-10 17:29:55.661 | error | (18900) Error: ENOENT: no such file or directory, copyfile  'admin/cover.png' ->  '/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/synology_0/cover.png'
synology.0 | 2020-05-10 17:29:55.659 | error | (18900) unhandled promise rejection: ENOENT: no such file or directory,  copyfile 'admin/cover.png' ->  '/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/synology_0/cover.png'
synology.0 | 2020-05-10 17:29:55.624 | info | (18900) starting. Version 0.1.9 in /opt/iobroker/node_modules/iobroker.synology, node: v12.16.3, js-controller: 3.1.4
synology.0 | 2020-05-10 17:29:23.331 | info | (18343) Terminated (NO_ERROR): Without reason
synology.0 | 2020-05-10 17:29:23.330 | info | (18343) terminating
synology.0 | 2020-05-10 17:29:23.307 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
synology.0 | 2020-05-10 17:29:23.307 | error | at /opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:8147:76
synology.0 | 2020-05-10 17:29:23.307 | error | at Object.main [as ready] (/opt/iobroker/node_modules/iobroker.synology/main.js:863:8)
synology.0 | 2020-05-10 17:29:23.307 | error | at Object.copyFileSync (fs.js:1800:3)
synology.0 | 2020-05-10 17:29:23.307 | error | (18343) Error: ENOENT: no such file or directory, copyfile  'admin/cover.png' ->  '/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/synology_0/cover.png'
synology.0 | 2020-05-10 17:29:23.304 | error | (18343) unhandled promise rejection: ENOENT: no such file or directory,  copyfile 'admin/cover.png' ->  '/opt/iobroker/node_modules/iobroker.js-controller/../../iobroker-data/synology_0/cover.png'
synology.0 | 2020-05-10 17:29:23.219 | info | (18343) starting. Version 0.1.9 in /opt/iobroker/node_modules/iobroker.synology, node: v12.16.3, js-controller: 3.1.4
synology.0 | 2020-05-10 17:28:50.585 | info | (18018) Terminated (NO_ERROR): Without reason

`

**Comment by Ilovegym66** [comment]
back to 0.1.8 is working fine.

**Comment by Ilovegym66** [comment]
fixed with 0.1.10 :-)
